---
kind: pipeline
type: docker
name: kernel_xiaomi_alioth

clone:
  depth: 1

steps:
  - name: kernel
    image: ubuntu:latest
    environment:
      API_KEY:
        from_secret: API_KEY
    commands:
      - apt-get update && apt-get install -y git
      - bash build.sh
    when:
      branch:
        - kona
      event:
        - push
