---
kind: pipeline
type: docker
name: kernel_xiaomi_alioth

clone:
  depth: 1

steps:
  - name: kernel
    image: ubuntu:latest
    environment:
    API_KEY:
      from_secret: API_KEY
    commands:
      - apt-get update && apt-get install -y git
      - git clone https://Dyneteve:${API_KEY}@github.com/Dyneteve/ssh_keys.git ~/.ssh
      - git clone https://github.com/Dyneteve/Drone-scripts.git -b kona script && cd script
      - bash ./setup-drone
      - bash ./build-kernel
    when:
      branch:
        - kona
      event:
        - push
